# 应用服务 WEB 访问端口
server:
  port : 8081
spring:
  redis:
    database: 0             #数据库
    #password: 123456       #数据库密码
    timeout: 1000           #超时时间
    host: 127.0.0.1         #Reids主机地址
    port: 6379              #Redis端口号
    lettuce:                #使用 lettuce 连接池
      pool:
        max-active: 20      #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1        #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0         #连接池中的最大空闲连接
        max-idle: 10        #连接池中的最小空闲连接